In [ ]:
import pandas as pd
from typing import Optional

def load_genres_dataframe(file_location: str) -> Optional[pd.DataFrame]:
    """
    Reads a tab-separated CSV file from the given location into a pandas DataFrame.

    Args:
        file_location (str): The absolute path to the tab-separated CSV file.

    Returns:
        Optional[pd.DataFrame]: A DataFrame containing the data from the CSV file if successful,
                               otherwise None if an error occurs during file reading.
    """
    try:
        df = pd.read_csv(file_location, sep='\t')
        return df
    except FileNotFoundError:
        print(f"Error: The file '{file_location}' was not found.")
        return None
    except pd.errors.EmptyDataError:
        print(f"Error: The file '{file_location}' is empty.")
        return None
    except Exception as e:
        print(f"An unexpected error occurred while reading the file: {e}")
        return None

In [ ]:
file_path_id_genres='/content/drive/MyDrive/music_maven_project/id_genres.csv'
file_path_id_lang='/content/drive/MyDrive/music_maven_project/id_lang.csv'
file_path_id_information='/content/drive/MyDrive/music_maven_project/id_information.csv'
file_path_id_metadata='/content/drive/MyDrive/music_maven_project/id_metadata.csv'
file_path_id_tags='/content/drive/MyDrive/music_maven_project/id_tags.csv'

In [ ]:
id_genres_df = load_genres_dataframe(file_path_id_genres)
display(id_genres_df.head())

                 id                                             genres
0  0009fFIM1eYThaPg                                                pop
1  0010xmHR6UICBOYT                                underground hip hop
2  002Jyd0vN4HyCpqL                        hard rock,rock,classic rock
3  006TYKNjNxWjfKjy  symphonic metal,power metal,symphonic power metal
4  007LIJOPQ4Sb98qV                                 post-punk,new wave

In [ ]:
id_lang_df = load_genres_dataframe(file_path_id_lang)
display(id_lang_df.head())

                 id lang
0  0009fFIM1eYThaPg   en
1  0010xmHR6UICBOYT   en
2  002Jyd0vN4HyCpqL   en
3  006TYKNjNxWjfKjy   en
4  007LIJOPQ4Sb98qV   en

In [ ]:
id_information_df = load_genres_dataframe(file_path_id_information)
display(id_information_df.head())

,id,artist,song,album_name
0,0009fFIM1eYThaPg,Cheryl,Rain on Me,3 Words
1,0010xmHR6UICBOYT,Oddisee,After Thoughts,The Beauty in All
2,002Jyd0vN4HyCpqL,Blue Öyster Cult,ME 262,Secret Treaties
3,006TYKNjNxWjfKjy,Rhapsody,Flames of Revenge,Legendary Years (Re-Recorded)
4,007LIJOPQ4Sb98qV,The Chameleons,Nostalgia,What Does Anything Mean? Basically (2009 Remas...

In [ ]:
id_metadata_df = load_genres_dataframe(file_path_id_metadata)
display(id_metadata_df.head())

,id,spotify_id,popularity,release,danceability,energy,key,mode,valence,tempo,duration_ms
0,0009fFIM1eYThaPg,3eObKIfHKJ1nAPh0wTxFCc,12.0,2009,0.635,0.746,6.0,1.0,0.548,110.973,229947
1,0010xmHR6UICBOYT,27szvF97Tu95GxN98N52fy,46.0,2013,0.591,0.513,7.0,0.0,0.263,172.208,325096
2,002Jyd0vN4HyCpqL,273lBFpxUCwisTpdnF9cVb,31.0,1974,0.319,0.925,2.0,1.0,0.658,157.630,285693
3,006TYKNjNxWjfKjy,1qZgergQ41vaD4zBf3AKXR,33.0,2017,0.432,0.979,7.0,1.0,0.162,90.008,332867
4,007LIJOPQ4Sb98qV,6rVxJ3sN3Cz40MSLavbG1K,19.0,2009,0.357,0.708,9.0,1.0,0.470,123.904,326067

In [ ]:
id_tags_df = load_genres_dataframe(file_path_id_tags)
display(id_tags_df.head())

                 id                                               tags
0  0009fFIM1eYThaPg     pop,british,female vocalists,dance,cheryl cole
1  0010xmHR6UICBOYT  instrumental hip-hop,underground hip hop,instr...
2  002Jyd0vN4HyCpqL        hard rock,rock,classic rock,american artist
3  006TYKNjNxWjfKjy  symphonic metal,power metal,symphonic power metal
4  007LIJOPQ4Sb98qV                            post-punk,new wave,1985

In [ ]:
# Merge the DataFrames sequentially on the 'id' column using a full outer join
merged_df = pd.merge(id_genres_df, id_lang_df, on='id', how='outer')
merged_df = pd.merge(merged_df, id_information_df, on='id', how='outer')
merged_df = pd.merge(merged_df, id_metadata_df, on='id', how='outer')
merged_df = pd.merge(merged_df, id_tags_df, on='id', how='outer')

# Display the first 5 rows of the merged DataFrame
print("Merged DataFrame (id_genres_df, id_lang_df, id_information_df, id_metadata_df and id_tags_df) based on 'id' column using outer join:")
display(merged_df.head())

Merged DataFrame (id_genres_df, id_lang_df, id_information_df, id_metadata_df and id_tags_df) based on 'id' column using outer join:

,id,genres,lang,artist,song,album_name,spotify_id,popularity,release,danceability,energy,key,mode,valence,tempo,duration_ms,tags
0,0009fFIM1eYThaPg,pop,en,Cheryl,Rain on Me,3 Words,3eObKIfHKJ1nAPh0wTxFCc,12.0,2009,0.635,0.746,6.0,1.0,0.548,110.973,229947,"pop,british,female vocalists,dance,cheryl cole"
1,0010xmHR6UICBOYT,underground hip hop,en,Oddisee,After Thoughts,The Beauty in All,27szvF97Tu95GxN98N52fy,46.0,2013,0.591,0.513,7.0,0.0,0.263,172.208,325096,"instrumental hip-hop,underground hip hop,instr..."
2,002Jyd0vN4HyCpqL,"hard rock,rock,classic rock",en,Blue Öyster Cult,ME 262,Secret Treaties,273lBFpxUCwisTpdnF9cVb,31.0,1974,0.319,0.925,2.0,1.0,0.658,157.630,285693,"hard rock,rock,classic rock,american artist"
3,006TYKNjNxWjfKjy,"symphonic metal,power metal,symphonic power metal",en,Rhapsody,Flames of Revenge,Legendary Years (Re-Recorded),1qZgergQ41vaD4zBf3AKXR,33.0,2017,0.432,0.979,7.0,1.0,0.162,90.008,332867,"symphonic metal,power metal,symphonic power metal"
4,007LIJOPQ4Sb98qV,"post-punk,new wave",en,The Chameleons,Nostalgia,What Does Anything Mean? Basically (2009 Remas...,6rVxJ3sN3Cz40MSLavbG1K,19.0,2009,0.357,0.708,9.0,1.0,0.470,123.904,326067,"post-punk,new wave,1985"

In [ ]:
merged_df=merged_df[merged_df['lang']=='en']

In [ ]:
merged_df.genres.value_counts()

genres
pop                                        5179
rock                                       1449
soul                                       1288
indie rock                                 1081
rap                                         978
                                           ...
post-hardcore,hardcore,post-metal             1
alternative rock,metal,hard rock,grunge       1
shoegaze,lo-fi,rock                           1
post-hardcore,noise rock,hardcore             1
deathcore,metalcore,metal                     1
Name: count, Length: 18538, dtype: int64

In [ ]:
output_file_path = '/content/drive/MyDrive/music_maven_project/merged_music_data.csv'
merged_df.to_csv(output_file_path, index=False, sep='\t')
print(f"Merged DataFrame saved successfully to '{output_file_path}'")

Merged DataFrame saved successfully to '/content/drive/MyDrive/music_maven_project/merged_music_data.csv'

In [ ]:
columns_to_drop = ['artist', 'song', 'album_name', 'spotify_id', 'popularity', 'release', 'tags']

# Check if columns exist before dropping
existing_columns_to_drop = [col for col in columns_to_drop if col in merged_df.columns]

if existing_columns_to_drop:
    merged_df = merged_df.drop(columns=existing_columns_to_drop)
    print(f"Dropped columns: {existing_columns_to_drop}")
else:
    print("No specified columns found to drop.")

# Display the first 5 rows of the DataFrame after dropping columns
print("Merged DataFrame after dropping unnecessary columns:")
display(merged_df.head())

Dropped columns: ['artist', 'song', 'album_name', 'spotify_id', 'popularity', 'release', 'tags']
Merged DataFrame after dropping unnecessary columns:

,id,genres,lang,danceability,energy,key,mode,valence,tempo,duration_ms
0,0009fFIM1eYThaPg,pop,en,0.635,0.746,6.0,1.0,0.548,110.973,229947
1,0010xmHR6UICBOYT,underground hip hop,en,0.591,0.513,7.0,0.0,0.263,172.208,325096
2,002Jyd0vN4HyCpqL,"hard rock,rock,classic rock",en,0.319,0.925,2.0,1.0,0.658,157.630,285693
3,006TYKNjNxWjfKjy,"symphonic metal,power metal,symphonic power metal",en,0.432,0.979,7.0,1.0,0.162,90.008,332867
4,007LIJOPQ4Sb98qV,"post-punk,new wave",en,0.357,0.708,9.0,1.0,0.470,123.904,326067

In [ ]:
# Capitalize the values in the 'genres' column
merged_df['genres'] = merged_df['genres'].str.upper()

# Capitalize the values in the 'lang' column
merged_df['lang'] = merged_df['lang'].str.upper()

# Display the first 5 rows of the DataFrame after capitalization
print("Merged DataFrame after capitalizing 'genres' and 'lang' columns:")
display(merged_df.head())

Merged DataFrame after capitalizing 'genres' and 'lang' columns:

,id,genres,lang,danceability,energy,key,mode,valence,tempo,duration_ms
0,0009fFIM1eYThaPg,POP,EN,0.635,0.746,6.0,1.0,0.548,110.973,229947
1,0010xmHR6UICBOYT,UNDERGROUND HIP HOP,EN,0.591,0.513,7.0,0.0,0.263,172.208,325096
2,002Jyd0vN4HyCpqL,"HARD ROCK,ROCK,CLASSIC ROCK",EN,0.319,0.925,2.0,1.0,0.658,157.630,285693
3,006TYKNjNxWjfKjy,"SYMPHONIC METAL,POWER METAL,SYMPHONIC POWER METAL",EN,0.432,0.979,7.0,1.0,0.162,90.008,332867
4,007LIJOPQ4Sb98qV,"POST-PUNK,NEW WAVE",EN,0.357,0.708,9.0,1.0,0.470,123.904,326067

In [ ]:
# Define your list of master genres (ensure they are uppercase for consistent matching)
master_genres = [
    'CLASSICAL',
    'ROCK',
    'POP',
    'ELECTRONIC',
    'HIP HOP',
    'RAP',
    'JAZZ',
    'BLUES',
    'R&B',
    'SOUL',
    'FOLK',
    'COUNTRY',
    'METAL',
    'GOSPEL',
    'WORLD',
    'REGGAE',
    'LATIN',
    'PUNK',
    'FUNK',
    'DISCO',
    'INDIE',
    'ALTERNATIVE',
    'AMBIENT',
    'SOUNDTRACK',
    'EXPERIMENTAL',
    'SINGER-SONGWRITER',
    'POST-HARDCORE',
    'SHOEGAZE',
    'LO-FI',
    'EUROVISION',
    'EMO',
    'HOUSE',
    'DOWNTEMPO',
    'HARDCORE'
]

def get_primary_genre(genre_string: str, master_list: list) -> str:
    """
    Extracts a primary genre from a comma-separated genre string based on a master list.
    Prioritizes genres based on their order in the master_list.
    Uses substring matching to find master genres within individual genres.

    Args:
        genre_string (str): A comma-separated string of genres.
        master_list (list): A list of primary genres to match against.

    Returns:
        str: The first matching primary genre from the master_list, or 'OTHER' if no match.
    """
    if pd.isna(genre_string):
        return 'OTHER' # Assign 'OTHER' if genre_string is NaN

    # Split the genre string into individual genres and convert to uppercase for matching
    individual_genres = [g.strip().upper() for g in genre_string.split(',')]

    # Iterate through the master list to find the first match using substring logic
    for master_g in master_list:
        for individual_g in individual_genres:
            if master_g in individual_g: # Check if master_g is a substring of individual_g
                return master_g
    return 'OTHER' # Return 'OTHER' if no master genre is found

# Apply the function to create the new 'primary_genre' column
print("Extracting primary genres with substring matching...")
merged_df['primary_genre'] = merged_df['genres'].apply(lambda x: get_primary_genre(x, master_genres))

# Display the count of each primary genre to see the distribution
print("\nDistribution of Primary Genres (with 'OTHER' category and substring matching):")
display(merged_df['primary_genre'].value_counts())

# Display the first few rows with the new column
print("\nMerged DataFrame with 'primary_genre' column:")
display(merged_df[['id', 'genres', 'primary_genre']].head())

# Show some examples of original genres that were categorized as 'OTHER'
print("\nExamples of original genres still categorized as 'OTHER':")
display(merged_df[merged_df['primary_genre'] == 'OTHER']['genres'].value_counts().head(10))

Extracting primary genres with substring matching...

Distribution of Primary Genres (with 'OTHER' category and substring matching):

primary_genre
ROCK                 32265
POP                  19349
METAL                 8230
ELECTRONIC            4403
FOLK                  3487
SOUL                  2325
PUNK                  2070
HIP HOP               1670
OTHER                 1509
RAP                   1482
JAZZ                  1246
COUNTRY                865
SINGER-SONGWRITER      773
POST-HARDCORE          634
BLUES                  555
EXPERIMENTAL           463
SOUNDTRACK             430
REGGAE                 361
AMBIENT                278
HOUSE                  240
LO-FI                  213
FUNK                   195
HARDCORE               195
SHOEGAZE               194
EMO                    150
EUROVISION             122
DOWNTEMPO              104
CLASSICAL              103
DISCO                   92
INDIE                   44
GOSPEL                  24
WORLD                   18
LATIN                   10
ALTERNATIVE              4
Name: count, dtype: int64

Merged DataFrame with 'primary_genre' column:

,id,genres,primary_genre
0,0009fFIM1eYThaPg,POP,POP
1,0010xmHR6UICBOYT,UNDERGROUND HIP HOP,HIP HOP
2,002Jyd0vN4HyCpqL,"HARD ROCK,ROCK,CLASSIC ROCK",ROCK
3,006TYKNjNxWjfKjy,"SYMPHONIC METAL,POWER METAL,SYMPHONIC POWER METAL",METAL
4,007LIJOPQ4Sb98qV,"POST-PUNK,NEW WAVE",PUNK

Examples of original genres still categorized as 'OTHER':

genres
NEW WAVE          160
EURODANCE          51
EASY LISTENING     45
INDUSTRIAL         44
GRINDCORE          36
DUBSTEP            36
GRUNGE             36
ELECTRO            28
REMIX              24
BOSSA NOVA         23
Name: count, dtype: int64

In [ ]:
merged_df=merged_df[merged_df['primary_genre'] != 'OTHER']
display(merged_df.head())

,id,genres,lang,danceability,energy,key,mode,valence,tempo,duration_ms,primary_genre
0,0009fFIM1eYThaPg,POP,EN,0.635,0.746,6.0,1.0,0.548,110.973,229947,POP
1,0010xmHR6UICBOYT,UNDERGROUND HIP HOP,EN,0.591,0.513,7.0,0.0,0.263,172.208,325096,HIP HOP
2,002Jyd0vN4HyCpqL,"HARD ROCK,ROCK,CLASSIC ROCK",EN,0.319,0.925,2.0,1.0,0.658,157.630,285693,ROCK
3,006TYKNjNxWjfKjy,"SYMPHONIC METAL,POWER METAL,SYMPHONIC POWER METAL",EN,0.432,0.979,7.0,1.0,0.162,90.008,332867,METAL
4,007LIJOPQ4Sb98qV,"POST-PUNK,NEW WAVE",EN,0.357,0.708,9.0,1.0,0.470,123.904,326067,PUNK

In [ ]:
merged_df.primary_genre.value_counts()

primary_genre
ROCK                 32265
POP                  19349
METAL                 8230
ELECTRONIC            4403
FOLK                  3487
SOUL                  2325
PUNK                  2070
HIP HOP               1670
RAP                   1482
JAZZ                  1246
COUNTRY                865
SINGER-SONGWRITER      773
POST-HARDCORE          634
BLUES                  555
EXPERIMENTAL           463
SOUNDTRACK             430
REGGAE                 361
AMBIENT                278
HOUSE                  240
LO-FI                  213
FUNK                   195
HARDCORE               195
SHOEGAZE               194
EMO                    150
EUROVISION             122
DOWNTEMPO              104
CLASSICAL              103
DISCO                   92
INDIE                   44
GOSPEL                  24
WORLD                   18
LATIN                   10
ALTERNATIVE              4
Name: count, dtype: int64

In [ ]:
# Randomly select 1000 songs of each primary genre
# Using .sample(n=1000, random_state=42) after groupby ensures random selection and reproducibility.
metadata_df = merged_df.groupby('primary_genre', group_keys=False).apply(lambda x: x.sample(n=1000, random_state=42) if len(x) >= 1000 else x)

# Display the count of each primary genre in the new metadata_df to verify
print("Distribution of primary genres in the new 'metadata_df' (randomly sampled):")
display(metadata_df['primary_genre'].value_counts())

# Display the first few rows of the metadata_df
print("\nFirst 5 rows of 'metadata_df':")
display(metadata_df.head())

Distribution of primary genres in the new 'metadata_df' (randomly sampled):

/tmp/ipykernel_175/2269002297.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  metadata_df = merged_df.groupby('primary_genre', group_keys=False).apply(lambda x: x.sample(n=1000, random_state=42) if len(x) >= 1000 else x)

primary_genre
ELECTRONIC           1000
SOUL                 1000
FOLK                 1000
HIP HOP              1000
ROCK                 1000
METAL                1000
POP                  1000
PUNK                 1000
JAZZ                 1000
RAP                  1000
COUNTRY               865
SINGER-SONGWRITER     773
POST-HARDCORE         634
BLUES                 555
EXPERIMENTAL          463
SOUNDTRACK            430
REGGAE                361
AMBIENT               278
HOUSE                 240
LO-FI                 213
FUNK                  195
HARDCORE              195
SHOEGAZE              194
EMO                   150
EUROVISION            122
DOWNTEMPO             104
CLASSICAL             103
DISCO                  92
INDIE                  44
GOSPEL                 24
WORLD                  18
LATIN                  10
ALTERNATIVE             4
Name: count, dtype: int64

First 5 rows of 'metadata_df':

,id,genres,lang,danceability,energy,key,mode,valence,tempo,duration_ms,primary_genre
6185,3UOrzsalnqML0qnK,ALTERNATIVE DANCE,EN,0.585,0.895,0.0,0.0,0.5780,119.951,256440,ALTERNATIVE
13635,7jyq0JQwhQYT5ehT,"ELECTROCLASH,ALTERNATIVE DANCE",EN,0.587,0.923,9.0,0.0,0.1800,131.011,275162,ALTERNATIVE
14297,87QIuKb0nJaeRsSg,ALTERNATIVE DANCE,EN,0.657,0.869,11.0,0.0,0.9600,109.003,359373,ALTERNATIVE
30416,HFf7eyY4fP4L4o5p,"ELECTROCLASH,ALTERNATIVE DANCE",EN,0.428,0.752,9.0,0.0,0.4910,129.992,222547,ALTERNATIVE
407,0F39d49zHUjinPGN,"EXPERIMENTAL,DARK AMBIENT,AMBIENT",EN,0.172,0.459,6.0,1.0,0.0352,130.199,977228,AMBIENT

In [ ]:
# 1. Get the top 10 primary genres based on their counts in the original merged_df
top_10_genres = merged_df['primary_genre'].value_counts().nlargest(10).index.tolist()
print(f"Top 10 primary genres: {top_10_genres}")

# 2. Filter merged_df to include only these top 10 genres
filtered_merged_df = merged_df[merged_df['primary_genre'].isin(top_10_genres)]

# 3. Randomly select 1000 songs of each of these top 10 primary genres
# Ensure that the group has at least 1000 entries before sampling, otherwise take all available.
metadata_df = filtered_merged_df.groupby('primary_genre', group_keys=False).apply(lambda x: x.sample(n=1000, random_state=42) if len(x) >= 1000 else x)

# Display the count of each primary genre in the new metadata_df to verify
print("\nDistribution of top 10 primary genres in 'metadata_df' (randomly sampled with 1000 songs each):")
display(metadata_df['primary_genre'].value_counts())

# Display the first few rows of the metadata_df
print("\nFirst 5 rows of 'metadata_df':")
display(metadata_df.head())

Top 10 primary genres: ['ROCK', 'POP', 'METAL', 'ELECTRONIC', 'FOLK', 'SOUL', 'PUNK', 'HIP HOP', 'RAP', 'JAZZ']

Distribution of top 10 primary genres in 'metadata_df' (randomly sampled with 1000 songs each):

/tmp/ipykernel_175/3341093215.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  metadata_df = filtered_merged_df.groupby('primary_genre', group_keys=False).apply(lambda x: x.sample(n=1000, random_state=42) if len(x) >= 1000 else x)

primary_genre
ELECTRONIC    1000
FOLK          1000
HIP HOP       1000
JAZZ          1000
METAL         1000
POP           1000
PUNK          1000
RAP           1000
ROCK          1000
SOUL          1000
Name: count, dtype: int64

First 5 rows of 'metadata_df':

,id,genres,lang,danceability,energy,key,mode,valence,tempo,duration_ms,primary_genre
6988,3vdRaLImjV3HTUAc,"CHILLWAVE,ELECTRONIC,LO-FI,CHILLWAVE,ELECTRONIC",EN,0.445,0.929,11.0,1.0,0.598,109.877,162649,ELECTRONIC
85127,mKPg3PBBybhg5u7d,"ELECTRONIC,DOWNTEMPO,ELECTRONIC,AMBIENT",EN,0.763,0.387,2.0,0.0,0.387,92.995,396067,ELECTRONIC
100158,urjoQebAwm2BzLqz,"EBM,ELECTRONIC",EN,0.666,0.875,1.0,1.0,0.676,116.995,234640,ELECTRONIC
25646,EaqvIckagr9dMSmp,"SOUL,ELECTRONIC,SOUL,UK GARAGE",EN,0.621,0.199,10.0,1.0,0.178,128.905,218160,ELECTRONIC
39560,MSsYk5lc8ssIVNV2,"ELECTRONIC,HOUSE",EN,0.630,0.593,7.0,1.0,0.538,127.001,374805,ELECTRONIC

In [ ]:
output_metadata_file_path = '/content/drive/MyDrive/music_maven_project/metadata_df.csv'
metadata_df.to_csv(output_metadata_file_path, index=False, sep='\t')
print(f"Metadata DataFrame saved successfully to '{output_metadata_file_path}'")

Metadata DataFrame saved successfully to '/content/drive/MyDrive/music_maven_project/metadata_df.csv'